### ISSUE TITLE
feature/HomePageUI/ 

### ISSUE THREAD

**Issue by MinKonKim** [kybaq/3-feet#2]
###  홈페이지(메인페이지)의 설계한 와이어 프레임 대로 ui를 작성한다.
![image](https://github.com/kybaq/3-feet/assets/57051139/f69c0653-ed19-4950-baea-e7763d30929b)

## To-Do
- [x] react-slick 사용해서 캐러셀 구현
- [x] 구단 별 이미지 버튼 생성

### 변경사항
1.  HomePage.jsx  UI 구현
2.  components 폴더에 , HomePageComponents 폴더 생성,
3.  Banner.jsx,  Carousel.jsx, CarouselItem.jsx, ClubButtons.jsx 생성
4.  components 폴더에 , IconButton 폴더 와 jsx 파일 생성
5. ".eslintrc.cjs" 에 "react/prop-types": "off", 추가했습니다.
6. "react-slick" ,"slick-carousel", "@supabase/supabase-js" 라이브러리 설치했습니다 . 병합 후, npm i 부탁드립니다.
7. ".gitIgnore" 에 이미지 파일은 무시하도록 설정했습니다.

###  2024.06.18

**Comment by kybaq** [comment]
HomPage -> HomePage 로 오타 수정 필요할 것 같습니다!
브랜치 이름 확인해주시면 좋을 것 같아요
